/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCard: typeof import('@nutui/nutui-taro')['Card']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutIcon: typeof import('@nutui/nutui-taro')['Icon']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
  }
}
